# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(701, 506)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 661, 471))
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.stackedWidget.addWidget(self.home)
        self.reduccion = QtWidgets.QWidget()
        self.reduccion.setObjectName("reduccion")
        self.layoutWidget = QtWidgets.QWidget(self.reduccion)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 651, 391))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.labelDireccionArchivo = QtWidgets.QLabel(self.layoutWidget)
        self.labelDireccionArchivo.setText("")
        self.labelDireccionArchivo.setObjectName("labelDireccionArchivo")
        self.gridLayout.addWidget(self.labelDireccionArchivo, 2, 1, 1, 1)
        self.pushButtonGuardarArchivoFiltrado = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonGuardarArchivoFiltrado.setObjectName("pushButtonGuardarArchivoFiltrado")
        self.gridLayout.addWidget(self.pushButtonGuardarArchivoFiltrado, 8, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 9, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 1, 1, 1)
        self.pushButtonBuscar = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonBuscar.setObjectName("pushButtonBuscar")
        self.gridLayout.addWidget(self.pushButtonBuscar, 6, 2, 1, 1)
        self.pushButtonAbrirArchivoCSV = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonAbrirArchivoCSV.setObjectName("pushButtonAbrirArchivoCSV")
        self.gridLayout.addWidget(self.pushButtonAbrirArchivoCSV, 2, 2, 1, 1)
        self.lineEditPalabrasClave = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditPalabrasClave.setObjectName("lineEditPalabrasClave")
        self.gridLayout.addWidget(self.lineEditPalabrasClave, 6, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.reduccion)
        self.neuronal = QtWidgets.QWidget()
        self.neuronal.setObjectName("neuronal")
        self.layoutWidget_2 = QtWidgets.QWidget(self.neuronal)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 5, 651, 461))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 14, 1, 1, 1)
        self.pushButtonAbrirArchivo_DataSet = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButtonAbrirArchivo_DataSet.setObjectName("pushButtonAbrirArchivo_DataSet")
        self.gridLayout_3.addWidget(self.pushButtonAbrirArchivo_DataSet, 2, 2, 1, 1)
        self.pushButtonBuscar_DataSet = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButtonBuscar_DataSet.setObjectName("pushButtonBuscar_DataSet")
        self.gridLayout_3.addWidget(self.pushButtonBuscar_DataSet, 6, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 6, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBoxSuicidio = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBoxSuicidio.setObjectName("checkBoxSuicidio")
        self.gridLayout_3.addWidget(self.checkBoxSuicidio, 9, 1, 1, 1)
        self.checkBoxTristeza = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBoxTristeza.setObjectName("checkBoxTristeza")
        self.gridLayout_3.addWidget(self.checkBoxTristeza, 6, 1, 1, 1)
        self.checkBoxMascota = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBoxMascota.setObjectName("checkBoxMascota")
        self.gridLayout_3.addWidget(self.checkBoxMascota, 13, 1, 1, 1)
        self.checkBoxUniversidad = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBoxUniversidad.setObjectName("checkBoxUniversidad")
        self.gridLayout_3.addWidget(self.checkBoxUniversidad, 10, 1, 1, 1)
        self.checkBoxEscuela = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBoxEscuela.setObjectName("checkBoxEscuela")
        self.gridLayout_3.addWidget(self.checkBoxEscuela, 11, 1, 1, 1)
        self.checkBoxFamilia = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBoxFamilia.setObjectName("checkBoxFamilia")
        self.gridLayout_3.addWidget(self.checkBoxFamilia, 12, 1, 1, 1)
        self.checkBoxDepresion = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBoxDepresion.setObjectName("checkBoxDepresion")
        self.gridLayout_3.addWidget(self.checkBoxDepresion, 8, 1, 1, 1)
        self.pushButtonEntrenar = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButtonEntrenar.setObjectName("pushButtonEntrenar")
        self.gridLayout_3.addWidget(self.pushButtonEntrenar, 13, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.labelDireccionArchivo_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.labelDireccionArchivo_2.setText("")
        self.labelDireccionArchivo_2.setObjectName("labelDireccionArchivo_2")
        self.gridLayout_3.addWidget(self.labelDireccionArchivo_2, 2, 1, 1, 1)
        self.checkBoxAnsiedad = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBoxAnsiedad.setObjectName("checkBoxAnsiedad")
        self.gridLayout_3.addWidget(self.checkBoxAnsiedad, 7, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 16, 0, 1, 1, QtCore.Qt.AlignRight)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 3, 0, 1, 1)
        self.lineEditIteraciones = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEditIteraciones.setObjectName("lineEditIteraciones")
        self.gridLayout_3.addWidget(self.lineEditIteraciones, 3, 1, 1, 1)
        self.resultado_Entrenamiento = QtWidgets.QLabel(self.layoutWidget_2)
        self.resultado_Entrenamiento.setText("")
        self.resultado_Entrenamiento.setObjectName("resultado_Entrenamiento")
        self.gridLayout_3.addWidget(self.resultado_Entrenamiento, 15, 1, 1, 2)
        self.stackedWidget.addWidget(self.neuronal)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 701, 21))
        self.menubar.setObjectName("menubar")
        self.menuBD = QtWidgets.QMenu(self.menubar)
        self.menuBD.setObjectName("menuBD")
        self.menuFrecuencia = QtWidgets.QMenu(self.menubar)
        self.menuFrecuencia.setObjectName("menuFrecuencia")
        self.menuRed_Neuronal = QtWidgets.QMenu(self.menubar)
        self.menuRed_Neuronal.setObjectName("menuRed_Neuronal")
        MainWindow.setMenuBar(self.menubar)
        self.itemCrearBd = QtWidgets.QAction(MainWindow)
        self.itemCrearBd.setObjectName("itemCrearBd")
        self.actionsadsad = QtWidgets.QAction(MainWindow)
        self.actionsadsad.setObjectName("actionsadsad")
        self.itemNube = QtWidgets.QAction(MainWindow)
        self.itemNube.setObjectName("itemNube")
        self.itemHistograma = QtWidgets.QAction(MainWindow)
        self.itemHistograma.setObjectName("itemHistograma")
        self.itemEntrenamiento = QtWidgets.QAction(MainWindow)
        self.itemEntrenamiento.setObjectName("itemEntrenamiento")
        self.menuBD.addAction(self.itemCrearBd)
        self.menuFrecuencia.addAction(self.itemNube)
        self.menuFrecuencia.addAction(self.itemHistograma)
        self.menuRed_Neuronal.addAction(self.itemEntrenamiento)
        self.menubar.addAction(self.menuBD.menuAction())
        self.menubar.addAction(self.menuFrecuencia.menuAction())
        self.menubar.addAction(self.menuRed_Neuronal.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Analizador"))
        self.label_3.setText(_translate("MainWindow", "Direccion del Archivo:"))
        self.pushButtonGuardarArchivoFiltrado.setText(_translate("MainWindow", "Guardar CSV Reducido"))
        self.label_9.setText(_translate("MainWindow", "Crear Base De Datos Reducido"))
        self.label_6.setText(_translate("MainWindow", "Palabras clave:"))
        self.label_5.setText(_translate("MainWindow", "Ingrese las palabras claves a filtrar, usando espacios entre cada palabra"))
        self.pushButtonBuscar.setText(_translate("MainWindow", "Buscar"))
        self.pushButtonAbrirArchivoCSV.setText(_translate("MainWindow", "Seleccionar"))
        self.label.setText(_translate("MainWindow", "Seleccione su archivo CSV"))
        self.label_14.setText(_translate("MainWindow", "Seleccione nuevas situaciones:"))
        self.label_2.setText(_translate("MainWindow", "Seleccione el archivo para entrenar la red"))
        self.pushButtonAbrirArchivo_DataSet.setText(_translate("MainWindow", "Seleccionar"))
        self.pushButtonBuscar_DataSet.setText(_translate("MainWindow", "Buscar"))
        self.label_13.setText(_translate("MainWindow", "Situaciones"))
        self.checkBoxSuicidio.setText(_translate("MainWindow", "Suicidio"))
        self.checkBoxTristeza.setText(_translate("MainWindow", "Tristeza"))
        self.checkBoxMascota.setText(_translate("MainWindow", "Mascota"))
        self.checkBoxUniversidad.setText(_translate("MainWindow", "Universidad"))
        self.checkBoxEscuela.setText(_translate("MainWindow", "Escuela"))
        self.checkBoxFamilia.setText(_translate("MainWindow", "Familia"))
        self.checkBoxDepresion.setText(_translate("MainWindow", "Depresion"))
        self.pushButtonEntrenar.setText(_translate("MainWindow", "Entrenar"))
        self.label_4.setText(_translate("MainWindow", "Direccion del Archivo:"))
        self.checkBoxAnsiedad.setText(_translate("MainWindow", "Ansiedad"))
        self.label_11.setText(_translate("MainWindow", "Red Neuronal"))
        self.label_15.setText(_translate("MainWindow", "Resultado:"))
        self.label_10.setText(_translate("MainWindow", "Numero de iteraciones"))
        self.menuBD.setTitle(_translate("MainWindow", "BD reducida"))
        self.menuFrecuencia.setTitle(_translate("MainWindow", "Frecuencia de palabras"))
        self.menuRed_Neuronal.setTitle(_translate("MainWindow", "Red Neuronal"))
        self.itemCrearBd.setText(_translate("MainWindow", "Crear BD Reducida"))
        self.actionsadsad.setText(_translate("MainWindow", "Nube de palabras"))
        self.itemNube.setText(_translate("MainWindow", "Nube de palabras"))
        self.itemHistograma.setText(_translate("MainWindow", "Histograma"))
        self.itemEntrenamiento.setText(_translate("MainWindow", "Entrenamiento"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

